// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Config/ItemConfig.proto
// Protobuf C++ Version: 5.29.0-dev

#include "Config/ItemConfig.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace config {
              template <typename>
PROTOBUF_CONSTEXPR Sheet1_ItemRewardEntry_DoNotUse::Sheet1_ItemRewardEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Sheet1_ItemRewardEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : Sheet1_ItemRewardEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct Sheet1_ItemRewardEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Sheet1_ItemRewardEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Sheet1_ItemRewardEntry_DoNotUseDefaultTypeInternal() {}
  union {
    Sheet1_ItemRewardEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Sheet1_ItemRewardEntry_DoNotUseDefaultTypeInternal _Sheet1_ItemRewardEntry_DoNotUse_default_instance_;

inline constexpr Sheet1::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        itemreward_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bonusitemreward_{nullptr},
        id_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Sheet1::Sheet1(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Sheet1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Sheet1DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Sheet1DefaultTypeInternal() {}
  union {
    Sheet1 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Sheet1DefaultTypeInternal _Sheet1_default_instance_;
}  // namespace config
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Config_2fItemConfig_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Config_2fItemConfig_2eproto = nullptr;
const ::uint32_t
    TableStruct_Config_2fItemConfig_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::config::Sheet1_ItemRewardEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::config::Sheet1_ItemRewardEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::config::Sheet1_ItemRewardEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::config::Sheet1_ItemRewardEntry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::config::Sheet1, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::config::Sheet1, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::config::Sheet1, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::config::Sheet1, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::config::Sheet1, _impl_.itemreward_),
        PROTOBUF_FIELD_OFFSET(::config::Sheet1, _impl_.bonusitemreward_),
        ~0u,
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::config::Sheet1_ItemRewardEntry_DoNotUse)},
        {12, 24, -1, sizeof(::config::Sheet1)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::config::_Sheet1_ItemRewardEntry_DoNotUse_default_instance_._instance,
    &::config::_Sheet1_default_instance_._instance,
};
const char descriptor_table_protodef_Config_2fItemConfig_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027Config/ItemConfig.proto\022\006config\032\017item/"
    "item.proto\"\264\001\n\006Sheet1\022\n\n\002Id\030\001 \001(\r\022\014\n\004Nam"
    "e\030\002 \001(\t\0222\n\nItemReward\030\003 \003(\0132\036.config.She"
    "et1.ItemRewardEntry\022)\n\017BonusItemReward\030\004"
    " \001(\0132\020.item.ItemReward\0321\n\017ItemRewardEntr"
    "y\022\013\n\003key\030\001 \001(\r\022\r\n\005value\030\002 \001(\r:\0028\001b\006proto"
    "3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Config_2fItemConfig_2eproto_deps[1] =
    {
        &::descriptor_table_item_2fitem_2eproto,
};
static ::absl::once_flag descriptor_table_Config_2fItemConfig_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Config_2fItemConfig_2eproto = {
    false,
    false,
    241,
    descriptor_table_protodef_Config_2fItemConfig_2eproto,
    "Config/ItemConfig.proto",
    &descriptor_table_Config_2fItemConfig_2eproto_once,
    descriptor_table_Config_2fItemConfig_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_Config_2fItemConfig_2eproto::offsets,
    file_level_enum_descriptors_Config_2fItemConfig_2eproto,
    file_level_service_descriptors_Config_2fItemConfig_2eproto,
};
namespace config {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              Sheet1_ItemRewardEntry_DoNotUse::Sheet1_ItemRewardEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              Sheet1_ItemRewardEntry_DoNotUse::Sheet1_ItemRewardEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              Sheet1_ItemRewardEntry_DoNotUse::Sheet1_ItemRewardEntry_DoNotUse() : SuperType() {}
              Sheet1_ItemRewardEntry_DoNotUse::Sheet1_ItemRewardEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* Sheet1_ItemRewardEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) Sheet1_ItemRewardEntry_DoNotUse(arena);
              }
              constexpr auto Sheet1_ItemRewardEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Sheet1_ItemRewardEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::MessageLite::ClassDataFull
                  Sheet1_ItemRewardEntry_DoNotUse::_class_data_ = {
                      ::google::protobuf::Message::ClassData{
                          &_Sheet1_ItemRewardEntry_DoNotUse_default_instance_._instance,
                          &_table_.header,
                          nullptr,  // OnDemandRegisterArenaDtor
                          nullptr,  // IsInitialized
                          &Sheet1_ItemRewardEntry_DoNotUse::MergeImpl,
                          ::google::protobuf::Message::GetNewImpl<Sheet1_ItemRewardEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                          &Sheet1_ItemRewardEntry_DoNotUse::SharedDtor,
                          static_cast<void (::google::protobuf::MessageLite::*)()>(
                              &Sheet1_ItemRewardEntry_DoNotUse::ClearImpl),
                              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                              ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                          PROTOBUF_FIELD_OFFSET(Sheet1_ItemRewardEntry_DoNotUse, _impl_._cached_size_),
                          false,
                      },
                      &Sheet1_ItemRewardEntry_DoNotUse::kDescriptorMethods,
                      &descriptor_table_Config_2fItemConfig_2eproto,
                      nullptr,  // tracker
              };
              const ::google::protobuf::MessageLite::ClassData* Sheet1_ItemRewardEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Sheet1_ItemRewardEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Sheet1_ItemRewardEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::config::Sheet1_ItemRewardEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Sheet1_ItemRewardEntry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Sheet1_ItemRewardEntry_DoNotUse, _impl_.value_)}},
    // uint32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Sheet1_ItemRewardEntry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Sheet1_ItemRewardEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 key = 1;
    {PROTOBUF_FIELD_OFFSET(Sheet1_ItemRewardEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 value = 2;
    {PROTOBUF_FIELD_OFFSET(Sheet1_ItemRewardEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

// ===================================================================

class Sheet1::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Sheet1>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Sheet1, _impl_._has_bits_);
};

void Sheet1::clear_bonusitemreward() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.bonusitemreward_ != nullptr) _impl_.bonusitemreward_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
Sheet1::Sheet1(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:config.Sheet1)
}
inline PROTOBUF_NDEBUG_INLINE Sheet1::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::config::Sheet1& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        itemreward_{visibility, arena, from.itemreward_},
        name_(arena, from.name_) {}

Sheet1::Sheet1(
    ::google::protobuf::Arena* arena,
    const Sheet1& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Sheet1* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.bonusitemreward_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::item::ItemReward>(
                              arena, *from._impl_.bonusitemreward_)
                        : nullptr;
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:config.Sheet1)
}
inline PROTOBUF_NDEBUG_INLINE Sheet1::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        itemreward_{visibility, arena},
        name_(arena) {}

inline void Sheet1::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, bonusitemreward_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, bonusitemreward_) +
               sizeof(Impl_::id_));
}
Sheet1::~Sheet1() {
  // @@protoc_insertion_point(destructor:config.Sheet1)
  SharedDtor(*this);
}
inline void Sheet1::SharedDtor(MessageLite& self) {
  Sheet1& this_ = static_cast<Sheet1&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  delete this_._impl_.bonusitemreward_;
  this_._impl_.~Impl_();
}

inline void* Sheet1::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Sheet1(arena);
}
constexpr auto Sheet1::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.itemreward_) +
          decltype(Sheet1::_impl_.itemreward_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.itemreward_) +
          decltype(Sheet1::_impl_.itemreward_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Sheet1), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Sheet1::PlacementNew_,
                                 sizeof(Sheet1));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Sheet1::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Sheet1_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Sheet1::MergeImpl,
            ::google::protobuf::Message::GetNewImpl<Sheet1>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
            &Sheet1::SharedDtor,
            ::google::protobuf::Message::GetClearImpl<Sheet1>(), &Sheet1::ByteSizeLong,
                &Sheet1::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Sheet1, _impl_._cached_size_),
            false,
        },
        &Sheet1::kDescriptorMethods,
        &descriptor_table_Config_2fItemConfig_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Sheet1::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 26, 2> Sheet1::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Sheet1, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::config::Sheet1>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .item.ItemReward BonusItemReward = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.bonusitemreward_)}},
    // uint32 Id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Sheet1, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.id_)}},
    // string Name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.name_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 Id = 1;
    {PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string Name = 2;
    {PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // map<uint32, uint32> ItemReward = 3;
    {PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.itemreward_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // .item.ItemReward BonusItemReward = 4;
    {PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.bonusitemreward_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::item::ItemReward>()},
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(Sheet1()._impl_.itemreward_)>(
        0, 0, 0, 13,
        13)},
  }}, {{
    "\15\0\4\0\0\0\0\0"
    "config.Sheet1"
    "Name"
  }},
};

PROTOBUF_NOINLINE void Sheet1::Clear() {
// @@protoc_insertion_point(message_clear_start:config.Sheet1)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.itemreward_.Clear();
  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.bonusitemreward_ != nullptr);
    _impl_.bonusitemreward_->Clear();
  }
  _impl_.id_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Sheet1::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Sheet1& this_ = static_cast<const Sheet1&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Sheet1::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Sheet1& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:config.Sheet1)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 Id = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_id(), target);
          }

          // string Name = 2;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "config.Sheet1.Name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // map<uint32, uint32> ItemReward = 3;
          if (!this_._internal_itemreward().empty()) {
            using MapType = ::google::protobuf::Map<::uint32_t, ::uint32_t>;
            using WireHelper = _pbi::MapEntryFuncs<::uint32_t, ::uint32_t,
                                           _pbi::WireFormatLite::TYPE_UINT32,
                                           _pbi::WireFormatLite::TYPE_UINT32>;
            const auto& field = this_._internal_itemreward();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    3, entry.first, entry.second, target, stream);
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    3, entry.first, entry.second, target, stream);
              }
            }
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .item.ItemReward BonusItemReward = 4;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                4, *this_._impl_.bonusitemreward_, this_._impl_.bonusitemreward_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:config.Sheet1)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Sheet1::ByteSizeLong(const MessageLite& base) {
          const Sheet1& this_ = static_cast<const Sheet1&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Sheet1::ByteSizeLong() const {
          const Sheet1& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:config.Sheet1)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<uint32, uint32> ItemReward = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_itemreward_size());
              for (const auto& entry : this_._internal_itemreward()) {
                total_size += _pbi::MapEntryFuncs<::uint32_t, ::uint32_t,
                                               _pbi::WireFormatLite::TYPE_UINT32,
                                               _pbi::WireFormatLite::TYPE_UINT32>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // string Name = 2;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
           {
            // .item.ItemReward BonusItemReward = 4;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.bonusitemreward_);
            }
          }
           {
            // uint32 Id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Sheet1::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Sheet1*>(&to_msg);
  auto& from = static_cast<const Sheet1&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:config.Sheet1)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.itemreward_.MergeFrom(from._impl_.itemreward_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.bonusitemreward_ != nullptr);
    if (_this->_impl_.bonusitemreward_ == nullptr) {
      _this->_impl_.bonusitemreward_ =
          ::google::protobuf::Message::CopyConstruct<::item::ItemReward>(arena, *from._impl_.bonusitemreward_);
    } else {
      _this->_impl_.bonusitemreward_->MergeFrom(*from._impl_.bonusitemreward_);
    }
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Sheet1::CopyFrom(const Sheet1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:config.Sheet1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Sheet1::InternalSwap(Sheet1* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.itemreward_.InternalSwap(&other->_impl_.itemreward_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.id_)
      + sizeof(Sheet1::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(Sheet1, _impl_.bonusitemreward_)>(
          reinterpret_cast<char*>(&_impl_.bonusitemreward_),
          reinterpret_cast<char*>(&other->_impl_.bonusitemreward_));
}

::google::protobuf::Metadata Sheet1::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace config
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Config_2fItemConfig_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
