// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Common/types.proto
// Protobuf C++ Version: 5.29.0-dev

#include "Common/types.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace common {
}  // namespace common
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Common_2ftypes_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Common_2ftypes_2eproto = nullptr;
const ::uint32_t TableStruct_Common_2ftypes_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_Common_2ftypes_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022Common/types.proto\022\006common*>\n\010ItemType"
    "\022\013\n\007UNKNOWN\020\000\022\n\n\006WEAPON\020\001\022\t\n\005ARMOR\020\002\022\016\n\n"
    "CONSUMABLE\020\003b\006proto3"
};
static ::absl::once_flag descriptor_table_Common_2ftypes_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Common_2ftypes_2eproto = {
    false,
    false,
    100,
    descriptor_table_protodef_Common_2ftypes_2eproto,
    "Common/types.proto",
    &descriptor_table_Common_2ftypes_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_Common_2ftypes_2eproto::offsets,
    file_level_enum_descriptors_Common_2ftypes_2eproto,
    file_level_service_descriptors_Common_2ftypes_2eproto,
};
namespace common {
const ::google::protobuf::EnumDescriptor* ItemType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Common_2ftypes_2eproto);
  return file_level_enum_descriptors_Common_2ftypes_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ItemType_internal_data_[] = {
    262144u, 0u, };
bool ItemType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace common
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Common_2ftypes_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
