// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Common/types.proto
// Protobuf C++ Version: 5.29.0-dev

#ifndef Common_2ftypes_2eproto_2epb_2eh
#define Common_2ftypes_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Common_2ftypes_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Common_2ftypes_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Common_2ftypes_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace common {
enum ItemType : int {
  UNKNOWN = 0,
  WEAPON = 1,
  ARMOR = 2,
  CONSUMABLE = 3,
  ItemType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ItemType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool ItemType_IsValid(int value);
extern const uint32_t ItemType_internal_data_[];
constexpr ItemType ItemType_MIN = static_cast<ItemType>(0);
constexpr ItemType ItemType_MAX = static_cast<ItemType>(3);
constexpr int ItemType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
ItemType_descriptor();
template <typename T>
const std::string& ItemType_Name(T value) {
  static_assert(std::is_same<T, ItemType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ItemType_Name().");
  return ItemType_Name(static_cast<ItemType>(value));
}
template <>
inline const std::string& ItemType_Name(ItemType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ItemType_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool ItemType_Parse(absl::string_view name, ItemType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ItemType>(
      ItemType_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace common


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::common::ItemType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::common::ItemType>() {
  return ::common::ItemType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Common_2ftypes_2eproto_2epb_2eh
