// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Item/item.proto
// Protobuf C++ Version: 5.29.0-dev

#include "Item/item.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace item {

inline constexpr ItemReward::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : item_num_{::uint64_t{0u}},
        item_cfg_id_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ItemReward::ItemReward(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ItemRewardDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItemRewardDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItemRewardDefaultTypeInternal() {}
  union {
    ItemReward _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItemRewardDefaultTypeInternal _ItemReward_default_instance_;
}  // namespace item
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Item_2fitem_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Item_2fitem_2eproto = nullptr;
const ::uint32_t
    TableStruct_Item_2fitem_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::item::ItemReward, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::item::ItemReward, _impl_.item_cfg_id_),
        PROTOBUF_FIELD_OFFSET(::item::ItemReward, _impl_.item_num_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::item::ItemReward)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::item::_ItemReward_default_instance_._instance,
};
const char descriptor_table_protodef_Item_2fitem_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017Item/item.proto\022\004item\"3\n\nItemReward\022\023\n"
    "\013item_cfg_id\030\001 \001(\r\022\020\n\010item_num\030\002 \001(\004b\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_Item_2fitem_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Item_2fitem_2eproto = {
    false,
    false,
    84,
    descriptor_table_protodef_Item_2fitem_2eproto,
    "Item/item.proto",
    &descriptor_table_Item_2fitem_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Item_2fitem_2eproto::offsets,
    file_level_enum_descriptors_Item_2fitem_2eproto,
    file_level_service_descriptors_Item_2fitem_2eproto,
};
namespace item {
// ===================================================================

class ItemReward::_Internal {
 public:
};

ItemReward::ItemReward(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:item.ItemReward)
}
ItemReward::ItemReward(
    ::google::protobuf::Arena* arena, const ItemReward& from)
    : ItemReward(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ItemReward::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ItemReward::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, item_num_),
           0,
           offsetof(Impl_, item_cfg_id_) -
               offsetof(Impl_, item_num_) +
               sizeof(Impl_::item_cfg_id_));
}
ItemReward::~ItemReward() {
  // @@protoc_insertion_point(destructor:item.ItemReward)
  SharedDtor(*this);
}
inline void ItemReward::SharedDtor(MessageLite& self) {
  ItemReward& this_ = static_cast<ItemReward&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ItemReward::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ItemReward(arena);
}
constexpr auto ItemReward::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ItemReward));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    ItemReward::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_ItemReward_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &ItemReward::MergeImpl,
            ::google::protobuf::Message::GetNewImpl<ItemReward>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
            &ItemReward::SharedDtor,
            ::google::protobuf::Message::GetClearImpl<ItemReward>(), &ItemReward::ByteSizeLong,
                &ItemReward::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(ItemReward, _impl_._cached_size_),
            false,
        },
        &ItemReward::kDescriptorMethods,
        &descriptor_table_Item_2fitem_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* ItemReward::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ItemReward::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::item::ItemReward>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 item_num = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ItemReward, _impl_.item_num_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ItemReward, _impl_.item_num_)}},
    // uint32 item_cfg_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ItemReward, _impl_.item_cfg_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ItemReward, _impl_.item_cfg_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 item_cfg_id = 1;
    {PROTOBUF_FIELD_OFFSET(ItemReward, _impl_.item_cfg_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 item_num = 2;
    {PROTOBUF_FIELD_OFFSET(ItemReward, _impl_.item_num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ItemReward::Clear() {
// @@protoc_insertion_point(message_clear_start:item.ItemReward)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.item_num_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.item_cfg_id_) -
      reinterpret_cast<char*>(&_impl_.item_num_)) + sizeof(_impl_.item_cfg_id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ItemReward::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ItemReward& this_ = static_cast<const ItemReward&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ItemReward::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ItemReward& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:item.ItemReward)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 item_cfg_id = 1;
          if (this_._internal_item_cfg_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_item_cfg_id(), target);
          }

          // uint64 item_num = 2;
          if (this_._internal_item_num() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_item_num(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:item.ItemReward)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ItemReward::ByteSizeLong(const MessageLite& base) {
          const ItemReward& this_ = static_cast<const ItemReward&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ItemReward::ByteSizeLong() const {
          const ItemReward& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:item.ItemReward)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 item_num = 2;
            if (this_._internal_item_num() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_item_num());
            }
            // uint32 item_cfg_id = 1;
            if (this_._internal_item_cfg_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_item_cfg_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ItemReward::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ItemReward*>(&to_msg);
  auto& from = static_cast<const ItemReward&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:item.ItemReward)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_item_num() != 0) {
    _this->_impl_.item_num_ = from._impl_.item_num_;
  }
  if (from._internal_item_cfg_id() != 0) {
    _this->_impl_.item_cfg_id_ = from._impl_.item_cfg_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ItemReward::CopyFrom(const ItemReward& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:item.ItemReward)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ItemReward::InternalSwap(ItemReward* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ItemReward, _impl_.item_cfg_id_)
      + sizeof(ItemReward::_impl_.item_cfg_id_)
      - PROTOBUF_FIELD_OFFSET(ItemReward, _impl_.item_num_)>(
          reinterpret_cast<char*>(&_impl_.item_num_),
          reinterpret_cast<char*>(&other->_impl_.item_num_));
}

::google::protobuf::Metadata ItemReward::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace item
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Item_2fitem_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
