// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Combat/combat_system.proto
// Protobuf C++ Version: 5.29.0-dev

#ifndef Combat_2fcombat_5fsystem_2eproto_2epb_2eh
#define Combat_2fcombat_5fsystem_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common/entities.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Combat_2fcombat_5fsystem_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Combat_2fcombat_5fsystem_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Combat_2fcombat_5fsystem_2eproto;
namespace combat {
class CombatEvent;
struct CombatEventDefaultTypeInternal;
extern CombatEventDefaultTypeInternal _CombatEvent_default_instance_;
}  // namespace combat
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace combat {

// ===================================================================


// -------------------------------------------------------------------

class CombatEvent final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:combat.CombatEvent) */ {
 public:
  inline CombatEvent() : CombatEvent(nullptr) {}
  ~CombatEvent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CombatEvent* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CombatEvent));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CombatEvent(
      ::google::protobuf::internal::ConstantInitialized);

  inline CombatEvent(const CombatEvent& from) : CombatEvent(nullptr, from) {}
  inline CombatEvent(CombatEvent&& from) noexcept
      : CombatEvent(nullptr, std::move(from)) {}
  inline CombatEvent& operator=(const CombatEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline CombatEvent& operator=(CombatEvent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CombatEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const CombatEvent* internal_default_instance() {
    return reinterpret_cast<const CombatEvent*>(
        &_CombatEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CombatEvent& a, CombatEvent& b) { a.Swap(&b); }
  inline void Swap(CombatEvent* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CombatEvent* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CombatEvent* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CombatEvent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CombatEvent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CombatEvent& from) { CombatEvent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CombatEvent* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "combat.CombatEvent"; }

 protected:
  explicit CombatEvent(::google::protobuf::Arena* arena);
  CombatEvent(::google::protobuf::Arena* arena, const CombatEvent& from);
  CombatEvent(::google::protobuf::Arena* arena, CombatEvent&& from) noexcept
      : CombatEvent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kParticipantsFieldNumber = 1,
    kEventIdFieldNumber = 2,
  };
  // repeated .common.Entity participants = 1;
  int participants_size() const;
  private:
  int _internal_participants_size() const;

  public:
  void clear_participants() ;
  ::common::Entity* mutable_participants(int index);
  ::google::protobuf::RepeatedPtrField<::common::Entity>* mutable_participants();

  private:
  const ::google::protobuf::RepeatedPtrField<::common::Entity>& _internal_participants() const;
  ::google::protobuf::RepeatedPtrField<::common::Entity>* _internal_mutable_participants();
  public:
  const ::common::Entity& participants(int index) const;
  ::common::Entity* add_participants();
  const ::google::protobuf::RepeatedPtrField<::common::Entity>& participants() const;
  // int32 eventId = 2;
  void clear_eventid() ;
  ::int32_t eventid() const;
  void set_eventid(::int32_t value);

  private:
  ::int32_t _internal_eventid() const;
  void _internal_set_eventid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:combat.CombatEvent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_CombatEvent_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CombatEvent& from_msg);
    ::google::protobuf::RepeatedPtrField< ::common::Entity > participants_;
    ::int32_t eventid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Combat_2fcombat_5fsystem_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CombatEvent

// repeated .common.Entity participants = 1;
inline int CombatEvent::_internal_participants_size() const {
  return _internal_participants().size();
}
inline int CombatEvent::participants_size() const {
  return _internal_participants_size();
}
inline ::common::Entity* CombatEvent::mutable_participants(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:combat.CombatEvent.participants)
  return _internal_mutable_participants()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::common::Entity>* CombatEvent::mutable_participants()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:combat.CombatEvent.participants)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_participants();
}
inline const ::common::Entity& CombatEvent::participants(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:combat.CombatEvent.participants)
  return _internal_participants().Get(index);
}
inline ::common::Entity* CombatEvent::add_participants() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::common::Entity* _add = _internal_mutable_participants()->Add();
  // @@protoc_insertion_point(field_add:combat.CombatEvent.participants)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::common::Entity>& CombatEvent::participants() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:combat.CombatEvent.participants)
  return _internal_participants();
}
inline const ::google::protobuf::RepeatedPtrField<::common::Entity>&
CombatEvent::_internal_participants() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.participants_;
}
inline ::google::protobuf::RepeatedPtrField<::common::Entity>*
CombatEvent::_internal_mutable_participants() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.participants_;
}

// int32 eventId = 2;
inline void CombatEvent::clear_eventid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eventid_ = 0;
}
inline ::int32_t CombatEvent::eventid() const {
  // @@protoc_insertion_point(field_get:combat.CombatEvent.eventId)
  return _internal_eventid();
}
inline void CombatEvent::set_eventid(::int32_t value) {
  _internal_set_eventid(value);
  // @@protoc_insertion_point(field_set:combat.CombatEvent.eventId)
}
inline ::int32_t CombatEvent::_internal_eventid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.eventid_;
}
inline void CombatEvent::_internal_set_eventid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eventid_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace combat


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Combat_2fcombat_5fsystem_2eproto_2epb_2eh
